#!/usr/bin/env python3
"""Build a compact catalog for the local WizDen docs snapshot.

The generated catalog is intentionally an index, not a copy of the docs. Agents
should use it to choose which local source documents to read for a task.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def ascii_clean(value: str) -> str:
    return value.encode("ascii", "replace").decode("ascii")


def catalog_clean(value: str) -> str:
    value = re.sub(r"<!--.*?-->", "", value).strip()
    value = re.sub(r"\b(fuck\w*|shit\w*)\b", "[redacted]", value, flags=re.IGNORECASE)
    return ascii_clean(value)


def headings(lines: list[str], limit: int = 6) -> list[str]:
    found: list[str] = []
    in_fence = False

    for raw in lines:
        line = raw.strip()

        if line.startswith("```"):
            in_fence = not in_fence
            continue

        if in_fence or not line.startswith("#"):
            continue

        marker, _, title = line.partition(" ")
        if not title or len(marker) > 3:
            continue

        title = catalog_clean(title.strip().replace("|", "\\|"))
        if title and title not in found:
            found.append(title)

        if len(found) >= limit:
            break

    return found


def build_catalog(docs_root: Path) -> str:
    files = sorted(docs_root.rglob("*.md"))
    sections: dict[str, list[Path]] = {}

    for path in files:
        rel = path.relative_to(docs_root)
        section = rel.parts[0] if len(rel.parts) > 1 else "(root)"
        sections.setdefault(section, []).append(path)

    lines: list[str] = [
        "# WizDen Docs Full Catalog",
        "",
        f"Docs root: `{ascii_clean(str(docs_root))}`.",
        "",
        "This file is generated by `scripts/build_wizden_catalog.py`. It catalogs every markdown file in the local docs snapshot so Shine agents can find the source document to read before editing code, content, resources, maps, UI, networking, admin tools, server hosting, or agent instructions.",
        "",
        "Use this as a routing index only. The canonical Shine behavior remains `.agents/rules` and `.agents/skills`; the local docs are reference material.",
        "",
        f"Total markdown files: {len(files)}.",
        "",
    ]

    for section in sorted(sections):
        lines.append(f"## {ascii_clean(section)}")
        lines.append("")
        lines.append("| Path | Lines | Heading map |")
        lines.append("| --- | ---: | --- |")

        for path in sections[section]:
            rel = ascii_clean(path.relative_to(docs_root).as_posix())
            text = path.read_text(encoding="utf-8", errors="replace")
            doc_lines = text.splitlines()
            heading_text = "; ".join(headings(doc_lines)) or "(no headings)"
            lines.append(f"| `{rel}` | {len(doc_lines)} | {heading_text} |")

        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--docs-root", default=r"D:\.avid\docs\src\en")
    parser.add_argument("--output", default="references/wizden-docs-full-catalog.md")
    args = parser.parse_args()

    docs_root = Path(args.docs_root)
    output = Path(args.output)

    if not docs_root.exists():
        raise SystemExit(f"Docs root does not exist: {docs_root}")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_catalog(docs_root), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
